baseURL = "https://synqark.github.io/Arktoon-Manual/"
languageCode = "ja-JP"
title = "How to use Arktoon-Shaders"
theme = "hugo-theme-learn"
canonifyurls = true

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"